version: '3.8'

services:
  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: sistema_educativo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_educativo
      MYSQL_USER: tecsup
      MYSQL_PASSWORD: tecsup123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./demo/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: unless-stopped

  # Backend Spring Boot
  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    container_name: sistema_educativo_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sistema_educativo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: tecsup
      SPRING_DATASOURCE_PASSWORD: tecsup123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: miClaveSecretaJWT2024SistemaEducativo
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

  # Frontend React
  frontend:
    build:
      context: ./reactFrontend
      dockerfile: Dockerfile
    container_name: sistema_educativo_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge 